# Generated by Django 4.2.13 on 2024-06-20 10:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(max_length=255, verbose_name='Тема')),
                ('status', models.CharField(choices=[('Не начато', 'Не начато'), ('В работе', 'В работе'), ('Требует внимания', 'Требует внимания'), ('Обсуждение', 'Обсуждение'), ('Выполнено', 'Выполнено'), ('Просрочено', 'Просрочено')], max_length=50, verbose_name='Статус')),
                ('open_topic', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время открытия топика')),
                ('deadline', models.DateTimeField(blank=True, null=True, verbose_name='Крайний срок')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_topic', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('personal_access', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_topic', to=settings.AUTH_USER_MODEL)),
                ('reflective', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reflective_topic', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
