# Generated by Django 4.2.13 on 2024-06-25 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_office'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='office',
        ),
    ]
