# Generated by Django 4.2.13 on 2024-06-25 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0002_alter_office_office'),
        ('accounts', '0005_user_office'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='office',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_office', to='office.office'),
        ),
    ]
