# Generated by Django 5.0.6 on 2024-06-18 13:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('Регистрация', 'Регистрация'), ('Звонок', 'Звонок'), ('Консультация', 'Консультация'), ('Лекция', 'Лекция'), ('Практика', 'Практика'), ('Стажировка', 'Стажировка'), ('Конец стажировки', 'Конец стажировки'), ('Мастер класс', 'Мастер класс'), ('Вопрос о счете', 'Вопрос о счете'), ('Школа трейда', 'Школа трейда'), ('Последняя практика', 'Последняя практика'), ('Открытие счета', 'Открытие счета'), ('Пополнение счета', 'Пополнение счета'), ('Встреча', 'Встреча')], max_length=50)),
                ('data', models.DateTimeField()),
                ('status', models.CharField(choices=[('Запланировано', 'Запланировано'), ('Обработано', 'Обработано'), ('Выполнено', 'Выполнено'), ('Просрочено', 'Просрочено')], max_length=50)),
                ('description', models.TextField(null=True)),
                ('in_usd', models.CharField(max_length=50)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_lead', to='lead.lead')),
                ('reflective', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reflective_manager', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
