# Generated by Django 5.0.6 on 2024-06-18 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0002_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='in_usd',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
