# Generated by Django 5.0.6 on 2024-06-18 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0004_alter_event_description_alter_event_in_usd'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
