# Generated by Django 5.0.6 on 2024-06-19 00:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0005_event_modified_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_client', to='lead.lead'),
        ),
        migrations.AlterField(
            model_name='event',
            name='reflective',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reflective_event', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='TopicCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('Не начато', 'Не начато'), ('В работе', 'В работе'), ('Требует внимания', 'Требует внимания'), ('Обсуждение', 'Обсуждение'), ('Выполнено', 'Выполнено'), ('Просрочено', 'Просрочено')], max_length=50)),
                ('open_topic', models.DateTimeField(default=django.utils.timezone.now)),
                ('deadline', models.DateTimeField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_topic', to=settings.AUTH_USER_MODEL)),
                ('personal_access', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_topic', to=settings.AUTH_USER_MODEL)),
                ('reflective', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reflective_topic', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
