# Generated by Django 5.0.6 on 2024-06-19 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0006_alter_event_client_alter_event_reflective_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='job_title',
            field=models.CharField(default='Стажер', max_length=255),
        ),
    ]
