# Generated by Django 5.0.6 on 2024-06-19 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0007_userinfo_job_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
