# Generated by Django 4.2.13 on 2024-06-25 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('registration', 'Регистрация'), ('call', 'Звонок'), ('consultation', 'Консультация'), ('lesson', 'Лекция'), ('practice', 'Практика'), ('internship', 'Стажировка'), ('end_internship', 'Конец стажировки'), ('master_class', 'Мастер класс'), ('question_check', 'Вопрос о счете'), ('school_of_trade', 'Школа трейда'), ('last_practice', 'Последняя практика'), ('open_check', 'Открытие счета'), ('add_check', 'Пополнение счета'), ('event', 'Встреча')], max_length=50, verbose_name='Тип события'),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('planned', 'Запланировано'), ('processed', 'Обработано'), ('complete', 'Выполнено'), ('failed', 'Просрочено')], max_length=50, verbose_name='Статус'),
        ),
    ]
