# Generated by Django 4.2.13 on 2024-06-25 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_eventcomment_remove_event_comment_event_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='comment',
        ),
        migrations.AddField(
            model_name='eventcomment',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='event_comment', to='events.event', verbose_name='Событие'),
            preserve_default=False,
        ),
    ]
