# Generated by Django 4.2.13 on 2024-06-25 11:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0007_event_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='events', to='events.eventcomment'),
        ),
        migrations.AddField(
            model_name='eventcomment',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='author_comment', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventcomment',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
