# Generated by Django 4.2.13 on 2024-06-25 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_event_comments_eventcomment_author_eventcomment_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='comments',
        ),
    ]
