# Generated by Django 4.2.13 on 2024-06-25 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_alter_lead_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='office',
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(blank=True, choices=[('vip', 'vip'), ('fuck_off', 'FUCK OFF'), ('all_agree', 'На все согласен'), ('potential', 'Потенциальный'), ('bnd', 'БнД'), ('birsha_work', 'Биржа труда'), ('fssp', 'ФССП'), ('bankrupt', 'Банкрот')], max_length=50, null=True, verbose_name='Статус'),
        ),
    ]
