# Generated by Django 4.2.13 on 2024-06-25 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0001_initial'),
        ('leads', '0003_remove_lead_office_alter_lead_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='office',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='lead_office', to='office.office'),
            preserve_default=False,
        ),
    ]
