# Generated by Django 4.2.13 on 2024-06-25 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_lead_office'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='first_name',
            field=models.CharField(default=0, max_length=55),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lead',
            name='gender',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lead',
            name='last_name',
            field=models.CharField(default=0, max_length=55),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lead',
            name='surname',
            field=models.CharField(default=0, max_length=55),
            preserve_default=False,
        ),
    ]
