# Generated by Django 4.2.13 on 2024-06-25 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office', models.CharField(default='БТ', max_length=50, verbose_name='Название офиса')),
                ('city', models.CharField(max_length=50, verbose_name='Город')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('region', models.CharField(max_length=255, verbose_name='Регион')),
                ('groupOffice', models.CharField(max_length=255, verbose_name='Группа Офисов')),
                ('payday', models.IntegerField(verbose_name='День выплат')),
            ],
        ),
    ]
