# Generated by Django 4.2.13 on 2024-06-25 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='office',
            name='office',
            field=models.CharField(max_length=50, verbose_name='Название офиса'),
        ),
    ]
